project 'ios.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
    react_native_path = './ReactComponents/node_modules/react-native'
  # Pods for ios
  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'
  
  # Third party deps
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  
  
  pod 'React', :path => react_native_path, :subspecs => [
  'Core’,
  'CxxBridge’,
  'RCTImage’,
  'RCTNetwork’,
  'RCTText’,
  'RCTWebSocket’,
  'RCTAnimation',
  'RCTLinkingIOS',
  'RCTActionSheet',
  'DevSupport'
  ]

end
